'use server'

import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'

export async function createIssue(formData: FormData) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  const title = formData.get('title') as string
  const description = formData.get('description') as string
  const team_id = formData.get('team_id') as string
  const status = formData.get('status') as string || 'todo'
  const priority = formData.get('priority') as string || 'no_priority'

  if (!title || !team_id) {
    throw new Error('Title and Team are required')
  }

  const { data: issue, error } = await supabase
    .from('issues')
    .insert({
      title,
      description,
      team_id,
      status,
      priority,
      creator_id: user.id,
      // number and identifier are generated by the db trigger
    })
    .select()
    .single()

  if (error) {
    console.error('Error creating issue:', error)
    throw new Error('Failed to create issue')
  }

  revalidatePath('/my-issues')
  redirect(`/issue/${issue.identifier}`)
}
